#!/usr/bin/python3
def raise_exception_msg(value):
    raise NameError(value)
